### ISSUE TITLE
Wrong resource URLs in META.yml of 0.002 release

### ISSUE THREAD

**Issue by eserte** [preaction/Git-ReleaseRepo#2]
Contents are:

```
resources:
  bugtracker: https://github.com/preaction/{{$dist->name}}/issues
  homepage: https://github.com/preaction/{{$dist->name}}
  repository: https://github.com/preaction/{{$dist->name}}.git
```
